### ISSUE TITLE
Topic suggestion: Building UIs programatically with SnapKit

### ISSUE THREAD

**Issue by edgarjcfn** [swift-berlin/swift-berlin.github.io#12]
I would like to show how to build UIs with Auto Layout without the help of Interface Builder, using https://github.com/SnapKit/SnapKit
Then also talk about the ongoing debate over the advantages/disadvantages of Interface Builder vs. declarative UIs.

**Comment by JensRavens** [comment]
I'm looking forward to that discussion :)

Is meetup 11 on sep 21st ok for you?

**Comment by edgarjcfn** [comment]
Yes, it sounds good

**Comment by JensRavens** [comment]
Hey Edgar,
I'm looking forward to your talk on monday. May I ask you to do a pull request to add your talk to this site? Otherwise it would be ok as well to just post the information here and I'll do it for you. What we need is:

Your Name
Title of the Talk
A short abstract (just a few words)
Links (like twitter, your company or a link to slideshare)
If you want to display another image then you github or twitter avatar, please include it as well

Thanks!

**Comment by edgarjcfn** [comment]
Cool! I'll do it through here because it's faster:

Presenters: Edgar Neto and Karolis Stasaitis
Title: Building UI Views Programatically with SnapKit
Abstract: We will show how to build UI Views programatically using SnapKit's DSL instead of Interface Builder. We will also expand the discussion about reuse of graphical components through composition (instead of inheritance). 
Twitter: Edgar @edgarjcfn and Karolis @carlossless
For avatars you can use our twitter ones.

Thanks for updating it for me :)
